version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.9.0-browsers

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - node-deps-{{ checksum "package.json" }}

    - run:
        name: install frontend packages
        command: |
          npm i

    - save_cache:
        paths:
        - ./node_modules
        key: node-deps-{{ checksum "package.json" }}

    - run:
        name: test
        command: |
          npm test

    - run:
        name: lint
        command: |
          mkdir -p reports
          npm run ci-test-lint

    - run:
        name: coverage
        environment:
          COVERALLS_REPO_TOKEN: "9tBxvG8hoJroIbSNdMMNY9kNKTFVgVhQd"
        command: |
          npm run coveralls
          mkdir -p reports/coverage
          mv coverage/* reports/coverage

    - store_test_results:
        path: reports
    - store_artifacts:
        path: reports
